name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  schedule:
    # everyday 11AM (UTC)
    - cron: '* 9 * * *'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [17, 21]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Build uber-jar with Gradle
        run: ./gradlew quarkusBuild -Dquarkus.package.type=uber-jar

#      - name: Build native image
#        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
